package tech.alomessi.vitra;

import android.annotation.SuppressLint;
import android.app.Activity;
import android.app.AlertDialog;
import android.app.Dialog;
import android.app.PendingIntent;
import android.appwidget.AppWidgetManager;
import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.ColorDrawable;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.provider.Settings;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.Gravity;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import android.widget.Button;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.HorizontalScrollView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Space;
import android.widget.Switch;
import android.widget.TextView;
import android.widget.Toast;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

import tech.alomessi.vitra.widget.ClockWidgetProvider;
import tech.alomessi.vitra.widget.DateWidgetProvider;
import tech.alomessi.vitra.widget.PrayerWidgetProvider;
import tech.alomessi.vitra.widget.SearchWidgetProvider;
import tech.alomessi.vitra.widget.SystemWidgetProvider;
import tech.alomessi.vitra.widget.WeatherWidgetProvider;

@SuppressLint("SetTextI18n")
public class MainActivity extends Activity {
    private static final int BG=0xff050505, CARD=0xff1b1b1b, CARD_2=0xff252525, TEXT=0xfff7f7f7,
        MUTED=0xff9b9b9f, BORDER=0xff3d3d3f, PURPLE=0xff9587ff, BLUE=0xff157eea;
    private SharedPreferences prefs; private boolean arabic; private String screen="home",category="All";
    private WidgetData selected=WidgetData.ALL.get(0); private FrameLayout root; private LinearLayout page;
    private final Set<String> favorites=new HashSet<>(); private int accent=PURPLE,opacity=76,radius=26,darkness=72,blur=18;

    @Override protected void onCreate(Bundle state){super.onCreate(state);configureWindow();prefs=getSharedPreferences("vitra",Context.MODE_PRIVATE);arabic=prefs.getBoolean("arabic",Locale.getDefault().getLanguage().equals("ar"));Set<String> saved=prefs.getStringSet("favorites",null);if(saved!=null)favorites.addAll(saved);accent=prefs.getInt("accent",PURPLE);opacity=prefs.getInt("opacity_int",76);radius=prefs.getInt("corner_int",26);darkness=prefs.getInt("darkness_int",72);blur=prefs.getInt("blur_int",18);DataRepository.refresh(this,false);if(!prefs.getBoolean("onboarded",false))showOnboarding();else render("home");}
    @SuppressWarnings("deprecation") private void configureWindow(){Window w=getWindow();w.setStatusBarColor(BG);w.setNavigationBarColor(BG);}

    private void showOnboarding(){
        root=new FrameLayout(this);root.setBackground(gradient(0xff02030a,0xff101650,0));root.setPadding(dp(24),dp(28),dp(24),dp(24));
        LinearLayout box=column();box.setGravity(Gravity.CENTER_HORIZONTAL);root.addView(box,new FrameLayout.LayoutParams(-1,-2,Gravity.CENTER));
        ImageView logo=new ImageView(this);logo.setImageResource(R.mipmap.ic_launcher);logo.setContentDescription("Vitra");box.addView(logo,new LinearLayout.LayoutParams(dp(86),dp(86)));
        TextView brand=text("V I T R A",30,TEXT,true);brand.setGravity(Gravity.CENTER);box.addView(brand,matchWrap(dp(18),dp(7)));
        TextView tag=text("EVERY WIDGET, YOUR WAY",12,0xffd8d8ed,false);tag.setLetterSpacing(.22f);tag.setGravity(Gravity.CENTER);box.addView(tag,matchWrap(0,dp(24)));
        FrameLayout showcase=new FrameLayout(this);showcase.setBackground(glass(30,.45f,0x55ffffff));showcase.setPadding(dp(12),dp(12),dp(12),dp(12));WidgetPreviewView preview=new WidgetPreviewView(this,WidgetData.ALL.get(10),false,PURPLE);showcase.addView(preview,new FrameLayout.LayoutParams(-1,dp(170)));box.addView(showcase,matchHeight(dp(194),0,dp(26)));
        Button ar=primaryButton("ابدأ بالعربية");ar.setOnClickListener(v->finishOnboarding(true));box.addView(ar,matchHeight(dp(56),0,dp(10)));Button en=secondaryButton("Continue in English");en.setOnClickListener(v->finishOnboarding(false));box.addView(en,matchHeight(dp(54),0,dp(18)));
        TextView note=text("No account · No first-launch permissions\nلا يحتاج إلى تسجيل أو أذونات عند البدء",11,0xffb5b7cc,false);note.setGravity(Gravity.CENTER);box.addView(note,matchWrap(0,0));applyInsets(root);setContentView(root);
    }
    private void finishOnboarding(boolean ar){arabic=ar;prefs.edit().putBoolean("arabic",ar).putBoolean("onboarded",true).apply();render("home");}

    private void render(String destination){
        screen=destination;root=new FrameLayout(this);root.setBackgroundColor(BG);root.setLayoutDirection(arabic?View.LAYOUT_DIRECTION_RTL:View.LAYOUT_DIRECTION_LTR);
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setClipToPadding(false);page=column();page.setPadding(dp(18),dp(10),dp(18),dp(42));scroll.addView(page,new ScrollView.LayoutParams(-1,-2));root.addView(scroll,new FrameLayout.LayoutParams(-1,-1));
        switch(destination){case"home":buildHome();break;case"search":buildSearch();break;case"wallpapers":buildWallpapers();break;case"favorites":buildFavorites();break;case"settings":buildSettings();break;case"appearance":buildAppearance();break;case"datetime":buildDateTime();break;case"weather":buildWeatherSettings();break;case"prayer":buildPrayerSettings();break;case"sync":buildSyncSettings();break;case"tutorials":buildTutorials();break;case"about":buildAbout();break;case"pro":buildStudio();break;case"detail":buildDetail();break;case"editor":buildEditor();break;default:buildHome();}
        applyInsets(root);setContentView(root);
    }

    private void buildHome(){
        page.addView(homeHeader(),matchHeight(dp(64),0,dp(14)));
        HorizontalScrollView hsv=new HorizontalScrollView(this);hsv.setHorizontalScrollBarEnabled(false);LinearLayout chips=row();String[] cats={"All","New","Clock","Digital","Date","Weather","Prayer","System","Search","Apps","People","Quotes","Counters","Sports"};for(String c:cats){Button b=chip(displayCategory(c),c.equals(category));b.setTag(c);b.setOnClickListener(v->{category=String.valueOf(v.getTag());render("home");});chips.addView(b,wrapHeight(dp(38),0,dp(8)));}hsv.addView(chips);page.addView(hsv,matchWrap(0,dp(18)));
        List<WidgetData> data=filter(category,"");TextView count=text(ar(data.size()+" تصميم ويدجت",""+data.size()+" WIDGET DESIGNS"),11,MUTED,true);count.setLetterSpacing(.16f);page.addView(count,matchWrap(0,dp(10)));LinearLayout catalog=column();page.addView(catalog,matchWrap(0,0));populateCatalog(catalog,data);
    }

    private FrameLayout homeHeader(){FrameLayout h=new FrameLayout(this);Button menu=circleButton("•••");menu.setContentDescription(ar("القائمة","Menu"));menu.setOnClickListener(v->showDrawer());h.addView(menu,new FrameLayout.LayoutParams(dp(48),dp(48),Gravity.START|Gravity.CENTER_VERTICAL));TextView brand=text("V I T R A",19,TEXT,true);brand.setLetterSpacing(.16f);brand.setGravity(Gravity.CENTER);h.addView(brand,new FrameLayout.LayoutParams(-1,-1));Button pro=circleButton("V");pro.setTextColor(PURPLE);pro.setOnClickListener(v->render("pro"));h.addView(pro,new FrameLayout.LayoutParams(dp(48),dp(48),Gravity.END|Gravity.CENTER_VERTICAL));return h;}

    private void showDrawer(){
        Dialog d=new Dialog(this);LinearLayout panel=column();panel.setPadding(dp(22),dp(30),dp(22),dp(24));panel.setBackgroundColor(0xff0d0d0e);panel.setLayoutDirection(arabic?View.LAYOUT_DIRECTION_RTL:View.LAYOUT_DIRECTION_LTR);
        TextView brand=text("VITRA",27,TEXT,true);brand.setLetterSpacing(.18f);panel.addView(brand,matchWrap(0,dp(4)));panel.addView(text(ar("كل ويدجت، بطريقتك","EVERY WIDGET, YOUR WAY"),10,PURPLE,true),matchWrap(0,dp(22)));
        LinearLayout studio=column();studio.setPadding(dp(16),dp(15),dp(16),dp(15));studio.setBackground(gradient(0xff282341,0xff151515,22));studio.addView(text("VITRA STUDIO",13,TEXT,true));studio.addView(text(ar("جميع الأدوات متاحة في هذه النسخة","All tools unlocked in this build"),11,MUTED,false),matchWrap(dp(4),0));studio.setOnClickListener(v->{d.dismiss();render("pro");});panel.addView(studio,matchWrap(0,dp(16)));
        String[] labels=arabic?new String[]{"الويدجت","البحث","الخلفيات","المفضلة","الشروحات","الإعدادات","حول التطبيق"}:new String[]{"Widgets","Search","Wallpapers","Favorites","Tutorials","Settings","About"};String[] routes={"home","search","wallpapers","favorites","tutorials","settings","about"};String[] icons={"▦","⌕","◒","♡","▷","⚙","i"};for(int i=0;i<routes.length;i++){final String route=routes[i];Button item=drawerButton(icons[i]+"   "+labels[i]);item.setOnClickListener(v->{d.dismiss();render(route);});panel.addView(item,matchHeight(dp(52),0,dp(4)));}
        Space space=new Space(this);panel.addView(space,new LinearLayout.LayoutParams(1,0,1));panel.addView(text("Vitra 1.1 · ALOMESSI TECH",10,0xff68686b,false),matchWrap(dp(16),0));d.setContentView(panel);Window w=d.getWindow();if(w!=null){w.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));w.setLayout((int)(getResources().getDisplayMetrics().widthPixels*.86f),-1);w.setGravity(Gravity.START);WindowManager.LayoutParams lp=w.getAttributes();lp.width=(int)(getResources().getDisplayMetrics().widthPixels*.86f);lp.height=WindowManager.LayoutParams.MATCH_PARENT;lp.gravity=Gravity.START;w.setAttributes(lp);}d.show();if(w!=null){WindowManager.LayoutParams lp=w.getAttributes();lp.width=(int)(getResources().getDisplayMetrics().widthPixels*.86f);lp.height=WindowManager.LayoutParams.MATCH_PARENT;w.setAttributes(lp);}}

    private void populateCatalog(LinearLayout target,List<WidgetData> items){target.removeAllViews();LinearLayout row=null;for(WidgetData item:items){if(item.span==2){if(row!=null&&row.getChildCount()>0){target.addView(row,matchWrap(0,dp(10)));row=null;}target.addView(widgetCard(item,true),matchHeight(dp(178),0,dp(12)));}else{if(row==null)row=row();row.addView(widgetCard(item,false),new LinearLayout.LayoutParams(0,dp(228),1));if(row.getChildCount()==1){Space gap=new Space(this);row.addView(gap,new LinearLayout.LayoutParams(dp(10),1));}else if(row.getChildCount()==3){target.addView(row,matchWrap(0,dp(10)));row=null;}}}if(row!=null&&row.getChildCount()>0){Space fill=new Space(this);row.addView(fill,new LinearLayout.LayoutParams(0,1,1));target.addView(row,matchWrap(0,dp(10)));}}
    private LinearLayout widgetCard(WidgetData item,boolean wide){LinearLayout card=column();WidgetPreviewView preview=new WidgetPreviewView(this,item,arabic,accent);card.addView(preview,new LinearLayout.LayoutParams(-1,wide?dp(140):dp(184)));TextView title=text(item.title(arabic),12,MUTED,false);title.setGravity(Gravity.CENTER);card.addView(title,matchWrap(dp(5),0));if(item.isNew){TextView badge=text(ar("جديد","NEW"),8,PURPLE,true);badge.setGravity(Gravity.CENTER);card.addView(badge,matchWrap(dp(2),0));}card.setContentDescription(item.title(arabic)+". "+item.subtitle(arabic));card.setOnClickListener(v->{selected=item;render("detail");});return card;}

    private void buildSearch(){page.addView(backHeader(ar("البحث","Search")),matchHeight(dp(58),0,dp(14)));EditText input=new EditText(this);input.setHint(ar("ابحث عن ساعة، طقس، صلاة...","Search clock, weather, prayer..."));input.setSingleLine(true);input.setTextColor(TEXT);input.setHintTextColor(MUTED);input.setTextSize(15);input.setPadding(dp(18),0,dp(18),0);input.setBackground(glass(22,.92f,BORDER));page.addView(input,matchHeight(dp(54),0,dp(18)));LinearLayout results=column();page.addView(results);populateCatalog(results,WidgetData.ALL);input.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){populateCatalog(results,filter("All",s.toString()));}public void afterTextChanged(Editable e){}});}
    private void buildFavorites(){page.addView(backHeader(ar("المفضلة","Favorites")),matchHeight(dp(58),0,dp(14)));List<WidgetData> list=new ArrayList<>();for(WidgetData d:WidgetData.ALL)if(favorites.contains(d.id))list.add(d);if(list.isEmpty()){TextView empty=text("♡\n"+ar("لا توجد مفضلات بعد\nاضغط القلب في صفحة أي تصميم","No favorites yet\nTap the heart on any design"),18,MUTED,false);empty.setGravity(Gravity.CENTER);page.addView(empty,matchWrap(dp(100),0));}else populateCatalog(page,list);}

    private void buildWallpapers(){page.addView(backHeader(ar("الخلفيات","Wallpapers")),matchHeight(dp(58),0,dp(6)));page.addView(text(ar("خلفيات مصممة لإظهار الزجاج بوضوح","WALLPAPERS MADE FOR GLASS"),11,MUTED,true),matchWrap(0,dp(18)));int[][] colors={{0xff061537,0xff1169a8},{0xff18172e,0xff5544a6},{0xff171717,0xff4d4d4d},{0xff091a24,0xff2a6475},{0xff241426,0xff703f69},{0xff0e1928,0xff304f88},{0xff26170e,0xff744329},{0xff07160f,0xff296447}};String[] names=arabic?new String[]{"أزرق عميق","ليلة بنفسجية","زجاج دخاني","محيط هادئ","وهج وردي","شفق بارد","غروب نحاسي","غابة داكنة"}:new String[]{"Deep blue","Violet night","Smoke glass","Quiet ocean","Rose glow","Cold aurora","Copper dusk","Dark forest"};for(int x=0;x<4;x++){LinearLayout line=row();for(int y=0;y<2;y++){int i=x*2+y,choice=i;LinearLayout card=column();card.setPadding(dp(14),dp(14),dp(14),dp(14));card.setBackground(gradient(colors[i][0],colors[i][1],24));Space s=new Space(this);card.addView(s,new LinearLayout.LayoutParams(1,dp(128)));card.addView(text(names[i],13,TEXT,true));card.setOnClickListener(v->{int[] a={0xff68a8ff,PURPLE,Color.WHITE,0xff78c9dd,0xffff9ed4,0xff8eaaff,0xffffb382,0xff78d49a};accent=a[choice];saveStyle();toast(ar("تم تطبيق النمط على المعاينات","Style applied to previews"));});line.addView(card,new LinearLayout.LayoutParams(0,dp(184),1));if(y==0)line.addView(new Space(this),new LinearLayout.LayoutParams(dp(10),1));}page.addView(line,matchWrap(0,dp(10)));}}

    private void buildSettings(){page.addView(backHeader(ar("الإعدادات","Settings")),matchHeight(dp(58),0,dp(14)));page.addView(settingSection(ar("المظهر","APPEARANCE"),new String[][]{{ar("المظهر والألوان","Appearance & colors"),ar("الثيم، اللون، الزجاج والخلفية","Theme, accent, glass and background"),"appearance"},{ar("التاريخ والوقت","Date & time"),ar("الصيغة، التقويم والأرقام","Format, calendar and numerals"),"datetime"}}));page.addView(settingSection(ar("المحتوى","CONTENT"),new String[][]{{ar("الطقس والموقع","Weather & location"),ar("المدينة والوحدات والأيقونات","City, units and icons"),"weather"},{ar("الصلاة والتقويم الهجري","Prayer & Hijri"),ar("طريقة الحساب والإزاحات","Calculation method and offsets"),"prayer"}}));page.addView(settingSection(ar("النظام","SYSTEM"),new String[][]{{ar("المزامنة والتحديث","Sync & live updates"),ar("البطارية، التحديث والاهتزاز","Battery, refresh and haptics"),"sync"},{ar("الشروحات","Tutorials"),ar("إضافة وتخصيص الويدجت","Add and customize widgets"),"tutorials"},{ar("حول Vitra","About Vitra"),"1.1.0 · ALOMESSI TECH","about"}}));}
    private LinearLayout settingSection(String title,String[][] items){LinearLayout box=column();TextView h=text(title,10,PURPLE,true);h.setLetterSpacing(.16f);box.addView(h,matchWrap(dp(10),dp(8)));for(String[] item:items){LinearLayout r=settingRow(item[0],item[1],v->render(item[2]));box.addView(r,matchHeight(dp(72),0,dp(8)));}return box;}
    private void buildAppearance(){subHeader(ar("المظهر والألوان","Appearance & colors"),ar("تحكم كامل في لغة الزجاج داخل التطبيق والويدجت","Control the glass language across app and widgets"));page.addView(optionTitle(ar("ثيم التطبيق","APP THEME")));page.addView(choiceRow(new String[]{"Midnight","Ocean","Aurora"},"theme"));page.addView(optionTitle(ar("لون التمييز","ACCENT COLOR")));page.addView(colorPalette(),matchWrap(0,dp(18)));page.addView(switchRow(ar("ألوان تلقائية من الخلفية","Auto colors from wallpaper"),"auto_colors",false),matchHeight(dp(62),0,dp(8)));page.addView(switchRow(ar("واجهة داكنة نقية","Pure black interface"),"pure_black",true),matchHeight(dp(62),0,dp(8)));page.addView(settingRow(ar("لغة التطبيق","App language"),arabic?"العربية":"English",v->{arabic=!arabic;prefs.edit().putBoolean("arabic",arabic).apply();render("appearance");}),matchHeight(dp(70),0,dp(8)));}
    private void buildDateTime(){subHeader(ar("التاريخ والوقت","Date & time"),ar("الصيغة والتقويم والأرقام المعروضة في الويدجت","Widget format, calendar and numerals"));page.addView(optionTitle(ar("صيغة الوقت","TIME FORMAT")));page.addView(choiceRow(new String[]{"Auto","12H","24H"},"time_format"));page.addView(optionTitle(ar("التقويم","CALENDAR")));page.addView(choiceRow(new String[]{"Gregorian","Hijri","Dual"},"calendar"));page.addView(settingRow(ar("أول يوم في الأسبوع","First day of week"),ar("السبت","Saturday"),null),matchHeight(dp(70),0,dp(8)));page.addView(settingRow(ar("نمط أسماء الشهور العربية","Arabic month names"),ar("قياسي","Standard"),null),matchHeight(dp(70),0,dp(8)));page.addView(switchRow(ar("استخدام أرقام النظام","Use system numerals"),"system_numerals",true),matchHeight(dp(62),0,dp(8)));page.addView(sliderBlock(ar("إزاحة التاريخ الهجري","Hijri offset"),0,4,2,null));}
    private void buildWeatherSettings(){subHeader(ar("الطقس والموقع","Weather & location"),ar("بيانات حقيقية مع تخزين محلي وآخر وقت تحديث","Live data with local cache and freshness"));page.addView(settingRow(ar("المدينة","City"),prefs.getString("city_name","صنعاء · Sana'a"),v->showCityDialog()),matchHeight(dp(72),0,dp(8)));page.addView(optionTitle(ar("درجة الحرارة","TEMPERATURE")));page.addView(choiceRow(new String[]{"Celsius","Fahrenheit"},"temperature"));page.addView(optionTitle(ar("سرعة الرياح","WIND SPEED")));page.addView(choiceRow(new String[]{"km/h","m/s","mph"},"wind"));page.addView(switchRow(ar("أيقونات الطقس الزجاجية","Glass weather icons"),"weather_icons",true),matchHeight(dp(62),0,dp(8)));page.addView(switchRow(ar("استخدام موقع الجهاز","Use device location"),"device_location",false),matchHeight(dp(62),0,dp(8)));page.addView(settingRow(ar("مصدر البيانات","Data source"),"Open-Meteo · HTTPS",null),matchHeight(dp(70),0,0));}
    private void buildPrayerSettings(){subHeader(ar("الصلاة والتقويم الهجري","Prayer & Hijri"),ar("إعدادات دقيقة للمواقيت حسب مدينتك","Precise prayer settings for your city"));page.addView(settingRow(ar("طريقة الحساب","Calculation method"),ar("رابطة العالم الإسلامي","Muslim World League"),v->showCalculationDialog()),matchHeight(dp(72),0,dp(8)));page.addView(optionTitle(ar("طريقة العصر","ASR METHOD")));page.addView(choiceRow(new String[]{"Standard","Hanafi"},"asr_method"));page.addView(switchRow(ar("إظهار الإقامة","Show Iqamah"),"show_iqamah",false),matchHeight(dp(62),0,dp(8)));page.addView(switchRow(ar("إظهار صلاة الجمعة","Show Jumu'ah on Friday"),"show_jumuah",true),matchHeight(dp(62),0,dp(8)));page.addView(switchRow(ar("إظهار الوقت المنقضي والمتبقي","Show elapsed and remaining"),"show_elapsed",true),matchHeight(dp(62),0,dp(8)));page.addView(sliderBlock(ar("الإزاحة بالدقائق","Minute offset"),0,20,10,null));page.addView(settingRow(ar("مصدر المواقيت","Prayer source"),"Aladhan · cached",null),matchHeight(dp(70),0,0));}
    private void buildSyncSettings(){subHeader(ar("المزامنة والتحديث","Sync & live updates"),ar("حافظ على دقة الوقت والطقس والصلاة","Keep time, weather and prayer fresh"));page.addView(switchRow(ar("التحديث الموثوق في الخلفية","Reliable background sync"),"reliable_sync",true),matchHeight(dp(62),0,dp(8)));page.addView(switchRow(ar("الاهتزاز عند اللمس","Vibrate on tap"),"vibrate",true),matchHeight(dp(62),0,dp(8)));page.addView(switchRow(ar("إخفاء زر إعدادات الويدجت","Hide widget settings icon"),"hide_settings_icon",false),matchHeight(dp(62),0,dp(8)));page.addView(settingRow(ar("تحسين البطارية","Battery optimization"),ar("فتح إعدادات النظام","Open system settings"),v->openBatterySettings()),matchHeight(dp(72),0,dp(8)));page.addView(settingRow(ar("أذونات التطبيق","App permissions"),ar("تطلب وقت الحاجة فقط","Requested just in time"),v->openAppSettings()),matchHeight(dp(72),0,dp(8)));page.addView(settingRow(ar("تحديث البيانات الآن","Refresh data now"),ar("الطقس ومواقيت الصلاة","Weather and prayer times"),v->{DataRepository.refresh(this,true);toast(ar("جارٍ تحديث البيانات","Refreshing data"));}),matchHeight(dp(72),0,0));}

    private void buildTutorials(){subHeader(ar("الشروحات","Tutorials"),ar("من المعاينة حتى الويدجت على شاشتك","From preview to a widget on your screen"));String[][] steps={{"01",ar("اختر التصميم","Choose a design"),ar("تصفح الفئات وافتح التصميم الذي يعجبك.","Browse categories and open a design you like.")},{"02",ar("خصّص الزجاج","Customize glass"),ar("عدّل الخلفية والشفافية والتمويه والخط.","Adjust background, opacity, blur and typography.")},{"03",ar("أضف الويدجت","Add the widget"),ar("اضغط إضافة ووافق من شاشة النظام.","Tap Add and confirm in the system picker.")},{"04",ar("غيّر الحجم","Resize it"),ar("اضغط مطولًا على الويدجت واسحب حدوده.","Long-press the widget and drag its handles.")}};for(String[] s:steps){LinearLayout card=row();card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(dp(16),dp(14),dp(16),dp(14));card.setBackground(glass(22,.80f,BORDER));TextView n=text(s[0],22,PURPLE,true);card.addView(n,new LinearLayout.LayoutParams(dp(54),-1));LinearLayout copy=column();copy.addView(text(s[1],15,TEXT,true));copy.addView(text(s[2],12,MUTED,false),matchWrap(dp(4),0));card.addView(copy,new LinearLayout.LayoutParams(0,-2,1));page.addView(card,matchHeight(dp(92),0,dp(10)));}}
    private void buildAbout(){subHeader(ar("حول Vitra","About Vitra"),"VITRA 1.1.0");ImageView logo=new ImageView(this);logo.setImageResource(R.mipmap.ic_launcher);page.addView(logo,matchHeight(dp(120),dp(16),dp(8)));TextView brand=text("V I T R A",28,TEXT,true);brand.setGravity(Gravity.CENTER);brand.setLetterSpacing(.18f);page.addView(brand,matchWrap(0,dp(4)));TextView by=text("BY ALOMESSI TECH",10,PURPLE,true);by.setGravity(Gravity.CENTER);by.setLetterSpacing(.16f);page.addView(by,matchWrap(0,dp(26)));page.addView(settingRow(ar("الخصوصية","Privacy"),ar("لا حساب · بيانات محلية · أذونات عند الحاجة","No account · local data · just-in-time permissions"),null),matchHeight(dp(76),0,dp(8)));page.addView(settingRow(ar("مصادر البيانات","Data sources"),"Open-Meteo · Aladhan",null),matchHeight(dp(72),0,dp(8)));page.addView(settingRow(ar("التوافق","Compatibility"),"Android 8+ · targetSdk 36",null),matchHeight(dp(72),0,dp(8)));page.addView(settingRow(ar("الإصدار","Version"),"1.1.0 (11)",null),matchHeight(dp(72),0,0));}
    private void buildStudio(){subHeader("VITRA STUDIO",ar("مجموعة احترافية كاملة بلا تسجيل","A complete professional collection without an account"));LinearLayout hero=column();hero.setGravity(Gravity.CENTER);hero.setPadding(dp(22),dp(26),dp(22),dp(26));hero.setBackground(gradient(0xff272145,0xff101011,28));hero.addView(text("30",48,TEXT,true));TextView label=text(ar("تصميمًا مستقلًا","INDEPENDENT DESIGNS"),11,PURPLE,true);label.setGravity(Gravity.CENTER);hero.addView(label);page.addView(hero,matchHeight(dp(170),dp(12),dp(18)));String[] features=arabic?new String[]{"ساعات تناظرية ورقمية","طقس وصلاة وتقويم مزدوج","بحث واختصارات ومجلدات","نظام وعدادات واقتباسات ورياضة","تحكم كامل في الزجاج والخطوط"}:new String[]{"Analog and digital clocks","Weather, prayer and dual calendar","Search, shortcuts and folders","System, counters, quotes and sports","Full glass and typography controls"};for(String f:features){page.addView(infoLine("✓",f),matchHeight(dp(52),0,dp(6)));}TextView included=text(ar("كل المميزات متاحة في نسخة Vitra الحالية","Everything is included in this Vitra build"),12,MUTED,false);included.setGravity(Gravity.CENTER);page.addView(included,matchWrap(dp(18),0));}

    private void buildDetail(){page.addView(backHeader(selected.title(arabic)),matchHeight(dp(58),0,dp(12)));WidgetPreviewView preview=new WidgetPreviewView(this,selected,arabic,accent);page.addView(preview,matchHeight(selected.span==2?dp(220):dp(330),0,dp(12)));LinearLayout badges=row();badges.addView(chip(selected.collection,true),wrapHeight(dp(34),0,dp(8)));badges.addView(chip(selected.span==2?"5×2 · 5×1":"2×2",false),wrapHeight(dp(34),0,dp(8)));badges.addView(chip(ar("الرئيسية والقفل","HOME + LOCK"),false),wrapHeight(dp(34),0,0));page.addView(badges,matchWrap(0,dp(18)));page.addView(text(selected.title(arabic),28,TEXT,true));page.addView(text(selected.subtitle(arabic),14,MUTED,false),matchWrap(dp(5),dp(18)));Button custom=primaryButton(ar("تخصيص التصميم","Customize design"));custom.setOnClickListener(v->render("editor"));page.addView(custom,matchHeight(dp(56),0,dp(9)));LinearLayout actions=row();Button add=secondaryButton(ar("إضافة إلى الشاشة","Add to screen"));add.setOnClickListener(v->requestPin());actions.addView(add,new LinearLayout.LayoutParams(0,dp(54),1));Button heart=secondaryButton(favorites.contains(selected.id)?"♥":"♡");heart.setOnClickListener(v->{toggleFavorite(selected.id);render("detail");});actions.addView(heart,new LinearLayout.LayoutParams(dp(62),dp(54)));page.addView(actions,matchWrap(0,dp(20)));page.addView(infoLine(ar("الأحجام","SIZES"),selected.span==2?"5×1 · 5×2 · 5×4":"2×2 · 3×3"),matchHeight(dp(58),0,dp(7)));page.addView(infoLine(ar("التوافق","COMPATIBILITY"),"Android 8+ · Samsung One UI"),matchHeight(dp(58),0,dp(7)));page.addView(infoLine(ar("المحتوى","CONTENT"),selected.category+" · "+selected.collection),matchHeight(dp(58),0,0));}

    private void buildEditor(){page.addView(backHeader(ar("تخصيص الويدجت","Customize widget")),matchHeight(dp(58),0,dp(10)));FrameLayout previewBox=new FrameLayout(this);previewBox.setBackground(gradient(0xff12193a,0xff030303,28));previewBox.setPadding(dp(22),dp(22),dp(22),dp(22));previewBox.addView(new WidgetPreviewView(this,selected,arabic,accent),new FrameLayout.LayoutParams(-1,-1));page.addView(previewBox,matchHeight(dp(260),0,dp(16)));page.addView(editorTabs());page.addView(optionTitle(ar("خلفية الزجاج","GLASS BACKGROUND")));page.addView(choiceRow(new String[]{"Clear glass","Fill","Gradient","Image"},"background"));page.addView(optionTitle(ar("المؤثر","EFFECT")));page.addView(choiceRow(new String[]{"Normal","Blur","Fractal"},"effect"));page.addView(sliderBlock(ar("الشفافية","Opacity"),25,100,opacity,v->opacity=v));page.addView(sliderBlock(ar("العتامة","Darkness"),0,100,darkness,v->darkness=v));page.addView(sliderBlock(ar("التمويه","Blur"),0,40,blur,v->blur=v));page.addView(sliderBlock(ar("استدارة الزوايا","Corner radius"),8,48,radius,v->radius=v));page.addView(optionTitle(ar("لون الإضاءة","HIGHLIGHT COLOR")));page.addView(colorPalette(),matchWrap(0,dp(14)));page.addView(switchRow(ar("التكيّف مع الخلفية","Adapt to wallpaper"),"adapt_wallpaper",true),matchHeight(dp(62),0,dp(8)));page.addView(switchRow(ar("إظهار زر الإعدادات","Show settings icon"),"show_widget_settings",true),matchHeight(dp(62),0,dp(16)));LinearLayout buttons=row();Button reset=secondaryButton(ar("إعادة ضبط","Reset"));reset.setOnClickListener(v->{accent=PURPLE;opacity=76;radius=26;darkness=72;blur=18;render("editor");});buttons.addView(reset,new LinearLayout.LayoutParams(0,dp(56),1));Button save=primaryButton(ar("حفظ وإضافة","Save & add"));save.setOnClickListener(v->{saveStyle();prefs.edit().putString("pending_widget_style",selected.id).apply();requestPin();});buttons.addView(save,new LinearLayout.LayoutParams(0,dp(56),1));page.addView(buttons);}
    private LinearLayout editorTabs(){LinearLayout tabs=row();String[] names=arabic?new String[]{"الخلفية","الزجاج","النص","الإجراء"}:new String[]{"Background","Glass","Text","Action"};for(int i=0;i<names.length;i++){TextView t=text(names[i],10,i==1?TEXT:MUTED,i==1);t.setGravity(Gravity.CENTER);if(i==1)t.setBackground(glass(18,.9f,BORDER));tabs.addView(t,new LinearLayout.LayoutParams(0,dp(42),1));}return tabs;}

    private void subHeader(String title,String subtitle){page.addView(backHeader(title),matchHeight(dp(58),0,dp(2)));page.addView(text(subtitle,13,MUTED,false),matchWrap(0,dp(16)));}
    private LinearLayout choiceRow(String[] choices,String key){LinearLayout r=row();String current=prefs.getString(key,choices[0]);for(String choice:choices){Button b=chip(choice,choice.equals(current));b.setOnClickListener(v->{prefs.edit().putString(key,choice).apply();render(screen);});r.addView(b,new LinearLayout.LayoutParams(0,dp(40),1));}return r;}
    private LinearLayout colorPalette(){LinearLayout colors=row();int[] palette={Color.WHITE,0xffa0a0a0,PURPLE,0xff6aa9ff,0xffff8fb8,0xffffb66a,0xff78d49a};for(int color:palette){Button dot=new Button(this);dot.setText(accent==color?"✓":"");dot.setTextColor(color==Color.WHITE?Color.BLACK:Color.WHITE);dot.setTextSize(11);dot.setPadding(0,0,0,0);dot.setBackground(circle(color,accent==color));dot.setOnClickListener(v->{accent=color;saveStyle();render(screen);});colors.addView(dot,new LinearLayout.LayoutParams(0,dp(46),1));}return colors;}
    private LinearLayout sliderBlock(String title,int min,int max,int value,IntValue listener){LinearLayout block=column();LinearLayout head=row();head.addView(text(title,14,TEXT,true),new LinearLayout.LayoutParams(0,-2,1));TextView number=text(String.valueOf(value),12,MUTED,false);number.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);head.addView(number,new LinearLayout.LayoutParams(dp(60),-1));block.addView(head);SeekBar bar=new SeekBar(this);bar.setMax(max-min);bar.setProgress(Math.max(0,value-min));bar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean user){int v=p+min;number.setText(String.valueOf(v));if(listener!=null)listener.set(v);}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){saveStyle();}});block.addView(bar,matchWrap(dp(2),dp(12)));return block;}
    private void showCalculationDialog(){String[] names={"Auto","Umm Al-Qura","Muslim World League","Egyptian General Authority","University of Karachi","ISNA","Dubai / IACAD","Qatar","Diyanet Turkey","Jafari"};new AlertDialog.Builder(this).setTitle(ar("طريقة الحساب","Calculation method")).setItems(names,(d,w)->{prefs.edit().putString("calculation_method",names[w]).apply();render("prayer");}).setNegativeButton(ar("إلغاء","Cancel"),null).show();}

    private LinearLayout settingRow(String title,String subtitle,View.OnClickListener click){LinearLayout r=row();r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(16),dp(10),dp(14),dp(10));r.setBackground(glass(21,.82f,BORDER));LinearLayout copy=column();copy.addView(text(title,15,TEXT,true));copy.addView(text(subtitle,11,MUTED,false),matchWrap(dp(3),0));r.addView(copy,new LinearLayout.LayoutParams(0,-2,1));if(click!=null){TextView arrow=text(ar("‹","›"),24,MUTED,false);arrow.setGravity(Gravity.CENTER);r.addView(arrow,new LinearLayout.LayoutParams(dp(36),-1));r.setOnClickListener(click);r.setClickable(true);r.setFocusable(true);}return r;}
    private LinearLayout switchRow(String title,String key,boolean initial){LinearLayout r=row();r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(16),dp(8),dp(10),dp(8));r.setBackground(glass(20,.82f,BORDER));r.addView(text(title,14,TEXT,true),new LinearLayout.LayoutParams(0,-2,1));Switch s=new Switch(this);s.setChecked(prefs.getBoolean(key,initial));s.setOnCheckedChangeListener((b,c)->prefs.edit().putBoolean(key,c).apply());r.addView(s);return r;}
    private LinearLayout infoLine(String left,String right){LinearLayout line=row();line.setGravity(Gravity.CENTER_VERTICAL);line.setPadding(dp(15),dp(8),dp(15),dp(8));line.setBackground(glass(19,.75f,BORDER));line.addView(text(left,11,MUTED,true),new LinearLayout.LayoutParams(0,-2,.45f));TextView value=text(right,12,TEXT,true);value.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);line.addView(value,new LinearLayout.LayoutParams(0,-1,.55f));return line;}
    private TextView optionTitle(String value){TextView t=text(value,10,PURPLE,true);t.setLetterSpacing(.14f);LinearLayout.LayoutParams p=matchWrap(dp(20),dp(8));t.setLayoutParams(p);return t;}
    private LinearLayout backHeader(String title){LinearLayout h=row();h.setGravity(Gravity.CENTER_VERTICAL);Button b=circleButton(ar("›","‹"));b.setContentDescription(ar("رجوع","Back"));b.setOnClickListener(v->onBackPressed());h.addView(b,new LinearLayout.LayoutParams(dp(48),dp(48)));TextView t=text(title,21,TEXT,true);t.setGravity(Gravity.CENTER);h.addView(t,new LinearLayout.LayoutParams(0,-1,1));Space end=new Space(this);h.addView(end,new LinearLayout.LayoutParams(dp(48),1));return h;}
    private Button circleButton(String value){Button b=new Button(this);b.setAllCaps(false);b.setText(value);b.setTextSize(16);b.setTextColor(TEXT);b.setPadding(0,0,0,0);b.setGravity(Gravity.CENTER);b.setMinHeight(0);b.setMinWidth(0);b.setBackground(circle(CARD_2,false));return b;}
    private Button drawerButton(String value){Button b=new Button(this);b.setAllCaps(false);b.setText(value);b.setTextSize(14);b.setTextColor(TEXT);b.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);b.setPadding(dp(14),0,dp(14),0);b.setBackgroundColor(Color.TRANSPARENT);return b;}
    private Button primaryButton(String value){Button b=new Button(this);b.setAllCaps(false);b.setText(value);b.setTextSize(15);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setTextColor(Color.BLACK);b.setGravity(Gravity.CENTER);b.setBackground(gradient(Color.WHITE,0xffcfcfcf,21));return b;}
    private Button secondaryButton(String value){Button b=new Button(this);b.setAllCaps(false);b.setText(value);b.setTextSize(14);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setTextColor(TEXT);b.setGravity(Gravity.CENTER);b.setBackground(glass(20,.92f,BORDER));return b;}
    private Button chip(String value,boolean active){Button b=new Button(this);b.setAllCaps(false);b.setText(value);b.setTextSize(11);b.setTextColor(active?TEXT:0xffd0d0d0);b.setPadding(dp(14),0,dp(14),0);b.setMinHeight(0);b.setMinWidth(0);b.setBackground(glass(18,active?.98f:.45f,active?0xff626264:BORDER));return b;}
    private TextView text(String value,float size,int color,boolean bold){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);t.setTypeface(Typeface.create("sans",bold?Typeface.BOLD:Typeface.NORMAL));t.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);t.setLineSpacing(0,1.08f);return t;}
    private LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);return l;}
    private GradientDrawable glass(int corner,float alpha,int border){GradientDrawable d=gradient(withAlpha(CARD_2,(int)(alpha*245)),withAlpha(CARD,(int)(alpha*235)),corner);d.setStroke(dp(1),border);return d;}
    private GradientDrawable gradient(int start,int end,int corner){GradientDrawable d=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{start,end});d.setCornerRadius(dp(corner));return d;}
    private GradientDrawable circle(int color,boolean selected){GradientDrawable d=new GradientDrawable();d.setShape(GradientDrawable.OVAL);d.setColor(color);d.setStroke(dp(selected?3:1),selected?Color.WHITE:BORDER);return d;}
    private int withAlpha(int color,int a){return Color.argb(Math.max(0,Math.min(255,a)),Color.red(color),Color.green(color),Color.blue(color));}
    @SuppressWarnings("deprecation") private void applyInsets(View view){final int l=view.getPaddingLeft(),t=view.getPaddingTop(),r=view.getPaddingRight(),b=view.getPaddingBottom();view.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(l+i.getSystemWindowInsetLeft(),t+i.getSystemWindowInsetTop(),r+i.getSystemWindowInsetRight(),b+i.getSystemWindowInsetBottom());return i;});view.requestApplyInsets();}
    private LinearLayout.LayoutParams matchHeight(int h,int top,int bottom){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,h);p.setMargins(0,top,0,bottom);return p;}private LinearLayout.LayoutParams matchWrap(int top,int bottom){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,top,0,bottom);return p;}private LinearLayout.LayoutParams wrapHeight(int h,int top,int end){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,h);p.setMargins(0,top,end,0);return p;}
    private int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}private String ar(String a,String e){return arabic?a:e;}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    private List<WidgetData> filter(String cat,String query){String q=query==null?"":query.trim().toLowerCase(Locale.ROOT);List<WidgetData> out=new ArrayList<>();for(WidgetData d:WidgetData.ALL){boolean categoryMatch=cat.equals("All")||(cat.equals("New")&&d.isNew)||d.category.equals(cat);boolean textMatch=q.isEmpty()||d.title(false).toLowerCase(Locale.ROOT).contains(q)||d.title(true).contains(q)||d.category.toLowerCase(Locale.ROOT).contains(q)||d.collection.toLowerCase(Locale.ROOT).contains(q);if(categoryMatch&&textMatch)out.add(d);}return out;}
    private String displayCategory(String v){if(!arabic)return v;switch(v){case"All":return"الكل";case"New":return"جديد";case"Clock":return"ساعة";case"Digital":return"رقمية";case"Date":return"تاريخ";case"Weather":return"طقس";case"Prayer":return"صلاة";case"System":return"النظام";case"Search":return"بحث";case"Apps":return"تطبيقات";case"People":return"أشخاص";case"Quotes":return"اقتباسات";case"Counters":return"عدادات";case"Sports":return"رياضة";default:return v;}}
    private void toggleFavorite(String id){if(!favorites.add(id))favorites.remove(id);prefs.edit().putStringSet("favorites",new HashSet<>(favorites)).apply();}
    private void saveStyle(){prefs.edit().putInt("accent",accent).putInt("opacity_int",opacity).putInt("corner_int",radius).putInt("darkness_int",darkness).putInt("blur_int",blur).apply();}
    private void showCityDialog(){String[] names=new String[DataRepository.CITIES.length];for(int i=0;i<names.length;i++)names[i]=DataRepository.CITIES[i][0];new AlertDialog.Builder(this).setTitle(ar("اختر المدينة","Choose city")).setItems(names,(dialog,which)->{String[] c=DataRepository.CITIES[which];prefs.edit().putString("city_name",c[0]).putLong("city_lat",Double.doubleToRawLongBits(Double.parseDouble(c[1]))).putLong("city_lon",Double.doubleToRawLongBits(Double.parseDouble(c[2]))).remove("weather_updated").remove("prayer_updated").apply();DataRepository.refresh(this,true);render("weather");}).setNegativeButton(ar("إلغاء","Cancel"),null).show();}
    private void openAppSettings(){try{Intent i=new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);i.setData(android.net.Uri.parse("package:"+getPackageName()));startActivity(i);}catch(Exception e){toast(ar("تعذر فتح الإعدادات","Unable to open settings"));}}
    private void openBatterySettings(){try{startActivity(new Intent(Settings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS));}catch(Exception e){toast(ar("تعذر فتح الإعدادات","Unable to open settings"));}}
    private void requestPin(){prefs.edit().putString("pending_widget_style",selected.id).apply();AppWidgetManager m=AppWidgetManager.getInstance(this);if(!m.isRequestPinAppWidgetSupported()){toast(ar("المشغل لا يدعم الإضافة المباشرة","Launcher does not support direct pinning"));return;}Bundle extras=new Bundle();extras.putString("vitra_style",selected.id);PendingIntent ok=PendingIntent.getActivity(this,100,new Intent(this,MainActivity.class),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);m.requestPinAppWidget(new ComponentName(this,providerFor(selected)),extras,ok);}
    private Class<?> providerFor(WidgetData d){switch(d.category){case"Date":return DateWidgetProvider.class;case"Weather":return WeatherWidgetProvider.class;case"Prayer":return PrayerWidgetProvider.class;case"Search":case"Apps":case"People":return SearchWidgetProvider.class;case"System":case"Sports":case"Quotes":case"Counters":case"Countdown":return SystemWidgetProvider.class;default:return ClockWidgetProvider.class;}}
    private interface IntValue{void set(int value);}
    @Override public void onBackPressed(){if(screen.equals("editor")){render("detail");return;}if(screen.equals("detail")){render("home");return;}if(screen.equals("appearance")||screen.equals("datetime")||screen.equals("weather")||screen.equals("prayer")||screen.equals("sync")){render("settings");return;}if(!screen.equals("home")){render("home");return;}super.onBackPressed();}
}
