package tech.alomessi.vitra;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.LinearGradient;
import android.graphics.Paint;
import android.graphics.RectF;
import android.graphics.Shader;
import android.view.View;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;

public final class WidgetPreviewView extends View {
    private final WidgetData data; private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);
    private final RectF r=new RectF(); private final boolean arabic; private final int accent;
    public WidgetPreviewView(Context context,WidgetData data,boolean arabic,int accent){super(context);this.data=data;this.arabic=arabic;this.accent=accent;setLayerType(View.LAYER_TYPE_SOFTWARE,null);setContentDescription(data.title(arabic));}
    @Override protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight(),m=Math.min(w,h),pad=m*.045f;r.set(pad,pad,w-pad,h-pad);p.setShader(new LinearGradient(0,0,w,h,new int[]{0xff303030,0xff151515,0xff242424},null,Shader.TileMode.CLAMP));p.setStyle(Paint.Style.FILL);p.setShadowLayer(18,0,8,0x99000000);c.drawRoundRect(r,m*.13f,m*.13f,p);p.clearShadowLayer();p.setShader(null);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(Math.max(1,m*.006f));p.setColor(0x55ffffff);c.drawRoundRect(r,m*.13f,m*.13f,p);p.setStyle(Paint.Style.FILL);p.setShader(new LinearGradient(0,pad,0,h*.48f,0x38ffffff,0x00ffffff,Shader.TileMode.CLAMP));c.drawRoundRect(new RectF(pad*1.15f,pad*1.15f,w-pad*1.15f,h*.55f),m*.11f,m*.11f,p);p.setShader(null);int s=data.style;if(s<=5)drawAnalog(c,w,h,s);else if(s==6)drawWorld(c,w,h);else if(s>=7&&s<=10)drawDigital(c,w,h,s);else if(s>=11&&s<=15)drawDate(c,w,h,s);else if(s==16||s==17)drawWeather(c,w,h);else if(s==18||s==19)drawPrayer(c,w,h,s);else if(s==20)drawSearch(c,w,h);else if(s==21||s==22)drawShortcuts(c,w,h,s);else if(s==23||s==24)drawSystem(c,w,h,s);else if(s==25)drawQuote(c,w,h);else if(s==26||s==27)drawCounter(c,w,h,s);else drawSports(c,w,h,s);}
    private void drawAnalog(Canvas c,float w,float h,int style){float cx=w*.5f,cy=h*.5f,rad=Math.min(w,h)*.34f;if(style==1||style==3){p.setColor(style==1?0x443f3f3f:0x552f2f2f);c.drawCircle(cx,cy,rad,p);p.setColor(0x55303030);c.drawCircle(cx,cy,rad*.43f,p);}Calendar cal=Calendar.getInstance();float minute=cal.get(Calendar.MINUTE),hour=cal.get(Calendar.HOUR)%12+minute/60f;for(int i=0;i<12;i++){double a=Math.PI*2*i/12-Math.PI/2;float rr=(style==2||style==3)?(i%3==0?5:0):(i%3==0?5:2);if(rr==0)continue;p.setColor(i%3==0?Color.WHITE:0x88ffffff);c.drawCircle(cx+(float)Math.cos(a)*rad*.86f,cy+(float)Math.sin(a)*rad*.86f,rr,p);if(style==0||style==5)text(c,String.valueOf(i==0?12:i),cx+(float)Math.cos(a)*rad*.68f,cy+(float)Math.sin(a)*rad*.68f+4,Math.max(10,rad*.13f),0xffdddddd,Paint.Align.CENTER,false);}if(style<=3)text(c,new SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date()),cx,cy-rad*.46f,rad*.15f,0xffbdbdbd,Paint.Align.CENTER,false);hand(c,cx,cy,hour/12f*360-90,rad*.48f,Math.max(5,rad*.045f),Color.WHITE);hand(c,cx,cy,minute/60f*360-90,rad*.72f,Math.max(3,rad*.028f),Color.WHITE);hand(c,cx,cy,(cal.get(Calendar.SECOND)/60f)*360-90,rad*.82f,Math.max(2,rad*.015f),0xffff1b2d);p.setColor(0xffff1b2d);c.drawCircle(cx,cy,Math.max(4,rad*.035f),p);text(c,new SimpleDateFormat("EEE",Locale.ENGLISH).format(new Date()).toUpperCase(),cx,cy+rad*.55f,rad*.15f,0xffc7c7c7,Paint.Align.CENTER,false);}
    private void drawWorld(Canvas c,float w,float h){String t=new SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date());text(c,arabic?"دبي":"Dubai",w*.24f,h*.34f,h*.10f,0xffbdbdbd,Paint.Align.CENTER,false);text(c,t,w*.24f,h*.62f,h*.20f,Color.WHITE,Paint.Align.CENTER,true);p.setColor(0xff3b3b3b);c.drawCircle(w*.5f,h*.49f,h*.19f,p);text(c,"-2",w*.5f,h*.55f,h*.17f,Color.WHITE,Paint.Align.CENTER,true);text(c,arabic?"بروكسل":"Brussels",w*.76f,h*.34f,h*.10f,0xffbdbdbd,Paint.Align.CENTER,false);text(c,"11:34",w*.76f,h*.62f,h*.20f,Color.WHITE,Paint.Align.CENTER,true);}
    private void drawDigital(Canvas c,float w,float h,int style){String t=new SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date());float size=style==10?h*.55f:(style==9?h*.44f:h*.52f);int col=(style==7||style==8)?0xff5f5f5f:Color.WHITE;text(c,t,w*.5f,h*.62f,size,col,Paint.Align.CENTER,true);if(style==10)text(c,new SimpleDateFormat("EEE · dd MMM",Locale.ENGLISH).format(new Date()).toUpperCase(),w*.5f,h*.82f,h*.095f,0xffc6c6c6,Paint.Align.CENTER,false);}
    private void drawDate(Canvas c,float w,float h,int style){Calendar cal=Calendar.getInstance();if(style==11||style==14){text(c,String.valueOf(cal.get(Calendar.YEAR)),w*.12f,h*.26f,h*.105f,0xffd8d8d8,Paint.Align.LEFT,false);text(c,(cal.get(Calendar.DAY_OF_YEAR)*100/365)+"%",w*.88f,h*.26f,h*.105f,0xffd8d8d8,Paint.Align.RIGHT,false);int total=style==11?92:31,active=style==11?cal.get(Calendar.DAY_OF_YEAR)*92/365:cal.get(Calendar.DAY_OF_MONTH);for(int i=0;i<total;i++){int cols=style==11?23:11;float x=w*.12f+(i%cols)*(w*.76f/(cols-1));float y=h*.43f+(i/cols)*h*.12f;p.setColor(i<active?Color.WHITE:0x334f4f4f);c.drawCircle(x,y,Math.max(2,h*.018f),p);}return;}if(style==12){text(c,new SimpleDateFormat("EEEE",Locale.ENGLISH).format(new Date()).toUpperCase(),w*.5f,h*.59f,h*.25f,Color.WHITE,Paint.Align.CENTER,false);return;}if(style==15){text(c,new SimpleDateFormat("dd MMMM yyyy",Locale.getDefault()).format(new Date()),w*.5f,h*.42f,h*.16f,Color.WHITE,Paint.Align.CENTER,false);text(c,"١٤٤٨ هـ  •  2026",w*.5f,h*.69f,h*.13f,0xffc4c4c4,Paint.Align.CENTER,false);return;}text(c,new SimpleDateFormat("dd",Locale.getDefault()).format(new Date()),w*.5f,h*.48f,h*.36f,0x88ffffff,Paint.Align.CENTER,true);text(c,new SimpleDateFormat("MMMM",Locale.ENGLISH).format(new Date()).toUpperCase(),w*.5f,h*.68f,h*.24f,Color.WHITE,Paint.Align.CENTER,false);text(c,new SimpleDateFormat("dd / MM / yyyy",Locale.getDefault()).format(new Date()),w*.5f,h*.83f,h*.085f,0xffbdbdbd,Paint.Align.CENTER,false);}
    private void drawWeather(Canvas c,float w,float h){text(c,arabic?"صنعاء":"Sana'a",w*.10f,h*.22f,h*.10f,0xffc5c5c5,Paint.Align.LEFT,false);text(c,"29°",w*.10f,h*.52f,h*.32f,Color.WHITE,Paint.Align.LEFT,true);p.setColor(Color.WHITE);c.drawCircle(w*.80f,h*.27f,h*.11f,p);p.setColor(0xffeeeeee);c.drawOval(new RectF(w*.73f,h*.25f,w*.91f,h*.40f),p);text(c,"H:29°  L:18°",w*.10f,h*.76f,h*.10f,0xffd0d0d0,Paint.Align.LEFT,false);text(c,"Updated 13m ago",w*.10f,h*.89f,h*.07f,0xff888888,Paint.Align.LEFT,false);}
    private void drawPrayer(Canvas c,float w,float h,int style){if(style==18){text(c,"الصلاة",w*.5f,h*.53f,h*.30f,Color.WHITE,Paint.Align.CENTER,false);text(c,"03:44",w*.5f,h*.78f,h*.16f,0xffcfcfcf,Paint.Align.CENTER,true);}else{text(c,arabic?"الصلاة القادمة":"NEXT PRAYER",w*.08f,h*.25f,h*.09f,0xffbdbdbd,Paint.Align.LEFT,false);text(c,arabic?"الظهر":"DHUHR",w*.08f,h*.53f,h*.18f,Color.WHITE,Paint.Align.LEFT,true);text(c,"12:20",w*.90f,h*.53f,h*.20f,Color.WHITE,Paint.Align.RIGHT,true);text(c,arabic?"العصر  03:46":"ASR  03:46",w*.08f,h*.78f,h*.10f,0xffc5c5c5,Paint.Align.LEFT,false);}}
    private void drawSearch(Canvas c,float w,float h){p.setColor(0x33ffffff);c.drawRoundRect(new RectF(w*.07f,h*.16f,w*.93f,h*.50f),h*.17f,h*.17f,p);text(c,"G",w*.13f,h*.39f,h*.18f,Color.WHITE,Paint.Align.CENTER,true);text(c,arabic?"ابحث في Google":"Search Google",w*.22f,h*.38f,h*.10f,0xffeeeeee,Paint.Align.LEFT,false);text(c,"●",w*.86f,h*.38f,h*.11f,Color.WHITE,Paint.Align.CENTER,false);String[] a={"✦","文","◉","●"};for(int i=0;i<4;i++){float x=w*(.23f+i*.18f);p.setColor(0x33ffffff);c.drawCircle(x,h*.73f,h*.13f,p);text(c,a[i],x,h*.78f,h*.14f,Color.WHITE,Paint.Align.CENTER,false);}}
    private void drawShortcuts(Canvas c,float w,float h,int style){String[] a=style==21?new String[]{"☎","✦","◒","◎"}:new String[]{"M","A","S","Y"};for(int i=0;i<4;i++){float x=w*(.17f+i*.22f);p.setColor(0x33ffffff);c.drawCircle(x,h*.48f,h*.18f,p);text(c,a[i],x,h*.55f,h*.17f,Color.WHITE,Paint.Align.CENTER,true);}text(c,style==21?(arabic?"تطبيقاتك":"YOUR APPS"):(arabic?"المفضّلون":"FAVORITES"),w*.5f,h*.82f,h*.09f,0xffb8b8b8,Paint.Align.CENTER,false);}
    private void drawSystem(Canvas c,float w,float h,int style){if(style==24){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(h*.055f);p.setColor(0x334f4f4f);c.drawCircle(w*.5f,h*.48f,h*.27f,p);p.setColor(accent);c.drawArc(new RectF(w*.5f-h*.27f,h*.21f,w*.5f+h*.27f,h*.75f),-90,302,false,p);p.setStyle(Paint.Style.FILL);text(c,"84%",w*.5f,h*.55f,h*.22f,Color.WHITE,Paint.Align.CENTER,true);}else{text(c,"Storage 68%",w*.08f,h*.30f,h*.12f,Color.WHITE,Paint.Align.LEFT,false);p.setColor(0x334f4f4f);c.drawRoundRect(new RectF(w*.08f,h*.48f,w*.92f,h*.57f),h*.045f,h*.045f,p);p.setColor(Color.WHITE);c.drawRoundRect(new RectF(w*.08f,h*.48f,w*.64f,h*.57f),h*.045f,h*.045f,p);text(c,"218 GB free",w*.08f,h*.78f,h*.10f,0xffa9a9a9,Paint.Align.LEFT,false);}}
    private void drawQuote(Canvas c,float w,float h){text(c,"“",w*.10f,h*.38f,h*.45f,0x55ffffff,Paint.Align.LEFT,false);text(c,arabic?"كل هدوء يبدأ من الداخل":"CALM BEGINS WITHIN",w*.5f,h*.48f,h*.15f,Color.WHITE,Paint.Align.CENTER,true);text(c,arabic?"حكمة اليوم":"DAILY WISDOM",w*.5f,h*.73f,h*.08f,0xffa9a9a9,Paint.Align.CENTER,false);}
    private void drawCounter(Canvas c,float w,float h,int style){text(c,style==26?(arabic?"التسبيح":"DHIKR"):(arabic?"المناسبة":"EVENT"),w*.5f,h*.25f,h*.10f,0xffbdbdbd,Paint.Align.CENTER,false);text(c,style==26?"033":"12",w*.5f,h*.64f,h*.42f,Color.WHITE,Paint.Align.CENTER,true);text(c,style==26?(arabic?"اضغط للعد":"TAP TO COUNT"):(arabic?"يومًا متبقيًا":"DAYS LEFT"),w*.5f,h*.84f,h*.09f,0xffa9a9a9,Paint.Align.CENTER,false);}
    private void drawSports(Canvas c,float w,float h,int style){if(style==29){p.setColor(0x331b8cff);c.drawRoundRect(new RectF(w*.07f,h*.25f,w*.93f,h*.72f),h*.22f,h*.22f,p);text(c,"G",w*.15f,h*.57f,h*.18f,Color.WHITE,Paint.Align.CENTER,true);text(c,arabic?"ابحث عن مباراة":"Search matches",w*.27f,h*.56f,h*.12f,0xffeeeeee,Paint.Align.LEFT,false);return;}text(c,"WORLD CUP 2026",w*.5f,h*.18f,h*.09f,Color.WHITE,Paint.Align.CENTER,true);text(c,"YEM  10:00 PM  KSA",w*.5f,h*.43f,h*.18f,Color.WHITE,Paint.Align.CENTER,true);text(c,"GROUP A",w*.5f,h*.62f,h*.08f,0xffbdbdbd,Paint.Align.CENTER,false);String[] rows={"1  Yemen     6 pts","2  Saudi      4 pts","3  Egypt       3 pts"};for(int i=0;i<3;i++)text(c,rows[i],w*.18f,h*(.76f+i*.09f),h*.075f,0xffd5d5d5,Paint.Align.LEFT,false);}
    private void hand(Canvas c,float cx,float cy,float angle,float length,float stroke,int color){double a=Math.toRadians(angle);p.setColor(color);p.setStrokeWidth(stroke);p.setStrokeCap(Paint.Cap.ROUND);c.drawLine(cx,cy,cx+(float)Math.cos(a)*length,cy+(float)Math.sin(a)*length,p);}
    private void text(Canvas c,String value,float x,float y,float size,int color,Paint.Align align,boolean bold){p.setShader(null);p.setStyle(Paint.Style.FILL);p.setColor(color);p.setTextSize(size);p.setTextAlign(align);p.setTypeface(android.graphics.Typeface.create("sans",bold?android.graphics.Typeface.BOLD:android.graphics.Typeface.NORMAL));c.drawText(value,x,y,p);}
}
